project_name: tikuAdapter
before:
  hooks:
    - sh buildweb.sh
builds:
  - main: ./cmd/adapter-service
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: '386'
    goos:
      - aix
      - android
      - darwin
      - dragonfly
      - freebsd
      - illumos
      - ios
      - js
      - linux
      - nacl
      - netbsd
      - openbsd
      - plan9
      - solaris
      - windows
      - zos
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
      - loong64
      - mips
      - mipsle
      - mips64
      - mips64le
      - ppc
      - ppc64
      - ppc64le
      - riscv64
      - s390
      - s390x
      - sparc
      - sparc64
      - wasm
    ldflags: "-s -w -extldflags '-static'"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
checksum:
  name_template: checksums.txt
changelog:
  sort: desc
  filters:
    exclude:
      - '^ci:'
      - '^CI:'
