project_name: tikuAdapter
before:
  hooks:
    - sh buildweb.sh
builds:
  - main: ./cmd/adapter-service
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: '386'
      # 移除了之前针对 sparc/sparc64 的特定 ignore，因为它们将从 goarch 列表中移除
      - goarch: amd64p32
      - goarch: mips64p32le
      - goarch: ppc
      - goarch: s390
      - goos: nacl
      - goos: zos
    goos:
      - aix
      - android
      - darwin
      - dragonfly
      - freebsd
      - illumos
      - ios
      - js
      - linux
      - netbsd
      - openbsd
      - plan9
      - solaris
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
      - loong64
      - mips
      - mipsle
      - mips64
      - mips64le
      # - mips64p32 # Plan9 相关，且不在 'go tool dist list' 的主要组合中
      - ppc64
      - ppc64le
      - riscv64
      - s390x
      # - sparc64 # 根据 'go tool dist list' 移除
      - wasm
    ldflags: "-s -w -extldflags '-static'"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
checksum:
  name_template: checksums.txt
changelog:
  sort: desc
  filters:
    exclude:
      - '^ci:'
      - '^CI:'
