project_name: tikuAdapter
before:
  hooks:
    - sh buildweb.sh
builds:
  - main: ./cmd/adapter-service
    ldflags: "-s -w -extldflags '-static'"
    env:
      - CGO_ENABLED=0 # 全局禁用 CGO
      - GO111MODULE=on
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: '386'
      # 以下是之前确认需要忽略的
      - goarch: amd64p32
      - goarch: mips64p32le
      - goarch: ppc
      - goarch: s390
      - goos: nacl
      - goos: zos
    goos:
      - aix
      - android
      - darwin
      - dragonfly
      - freebsd
      - illumos
      - ios
      - js
      - linux
      - netbsd
      - openbsd
      - plan9
      - solaris
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
      - loong64
      - mips
      - mipsle
      - mips64
      - mips64le
      # - mips64p32 # Plan9 相关，且不在 'go tool dist list' 的主要组合中, 保持移除
      - ppc64
      - ppc64le
      - riscv64
      - s390x
      - wasm
    overrides:
      - goos: android
        goarch: amd64
        env:
          - CGO_ENABLED=1 # 仅为 android/amd64 启用 CGO
      - goos: android # 通常 android 的其他架构也可能需要 CGO
        goarch: arm
        env:
          - CGO_ENABLED=1
      - goos: android
        goarch: arm64
        env:
          - CGO_ENABLED=1
      - goos: android
        goarch: '386'
        env:
          - CGO_ENABLED=1
      # iOS 构建也总是需要 CGO
      - goos: ios
        goarch: amd64 # simulator
        env:
          - CGO_ENABLED=1
      - goos: ios
        goarch: arm64 # device
        env:
          - CGO_ENABLED=1
checksum:
  name_template: checksums.txt
changelog:
  sort: desc
  filters:
    exclude:
      - '^ci:'
      - '^CI:'
